[tool.poetry]
name = "hcw-api"
version = "0.0.1"
authors = ["Ian Robinson <ian.robinson27@nhs.net>", "Sat Thakor <satyarajsinh.thakor1@nhs.net>"]
description = "Healthcare Worker API for fetching healthcare worker information"
readme = "README.md"
packages = [{include = "*/*", from="src"}, {include = "*", from="src"}, {include = "*", from = "integration_tests"}]

[tool.poetry.dependencies]
python = "^3.12"
boto3 = "^1.35.33"
pytest = "^8.4.0"
aws-lambda-powertools = "^3.1.0"
pydantic = "1.10.18"
setuptools = "^80.9.0"
jproperties = "^2.1.2"
requests = "^2.32.3"
pyjwt = "^2.9.0"
cryptography = "^43.0.1"
proxygen-cli = "^2.1.14"
coverage = "^7.6.4"
ldap3 = "^2.9.1"
jsonpickle = "^4.0.0"
pytest-env = "^1.1.5"

[tool.poetry.scripts]
start = "main:local_start"
token = "utils.generate_access_token:generate_from_command_line"

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.pytest_env]
UNIT_TESTING = "True"

[build-system]
requires = ["poetry-core"]
