# This is triggered as part of the codepipeline pipelines to deploy a specific build to an environment. It takes in
# the environment name and the s3 filename of the build zip for the lambda.
# There is one instance of this job in every HCW AWS account, with it responsible for making changes any infrastructure
# changes as required.
version: 0.2

env:
  variables:
    environment_name: ""
    account_name: ""
    app_s3_filename: ""

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - terraform --version
      - pip install proxygen-cli
      - wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
      - chmod +x /usr/bin/yq
  build:
    commands:
      - cd infrastructure
      - terraform init
      - terraform workspace select -or-create ${environment_name}
      - terraform plan -var-file="environments/${account_name}.tfvars" -var "app_s3_filename=${app_s3_filename}" -out tf.plan
      - terraform apply tf.plan
      - |
        if expr "${environment_name}" : "ft" >/dev/null; then
          # TODO: put back to ft instead of pr for testing
          # Since we're deploying to ft we want to make sure we deploy the mgmt infra too (we don't do this on
          # every branch otherwise it'll conflict)
          # There's two parts to this:
          # 1) The management account itself
          # 2) Resources shared between environments within an account
          # So we're going to do both deployments here
          terraform workspace select management
          terraform plan -var-file="environments/mgmt.tfvars" -out tf.plan
          terraform apply tf.plan
          terraform workspace select mgmt
          terraform plan -var-file="environments/${account_name}.tfvars" -out tf.plan
          terraform apply tf.plan
        fi

