# This job is triggered directly by webhooks when a PR is closed or merged. It destroys the relevant dev
# environment to save resources.
version: 0.2

env:
  variables:
    apim_private_key_secret_arn: ""

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - terraform --version
      - pip install proxygen-cli
      - wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
      - chmod +x /usr/bin/yq
  build:
    commands:
      - |
        if expr "${CODEBUILD_SOURCE_VERSION}" : "pr/.*"  >/dev/null; then
          export env_name="${CODEBUILD_SOURCE_VERSION/\//-}"
          # Clean up proxygen instance first, before destroying terraform infrastructure
          echo "Cleaning up proxygen instance for ${env_name}"
          cd infrastructure
          ./modules/hcw-api/apim_instance_delete.sh "${env_name}" "internal-dev" "${apim_private_key_secret_arn}"

          # Now proceed with terraform cleanup
          terraform init

          terraform workspace select ${env_name}
          terraform destroy -var-file="environments/dev.tfvars" --auto-approve

          # Need to swap to a different workspace before we can delete this one
          terraform workspace select ft
          terraform workspace delete ${env_name}
        fi
