openapi: 3.0.3
info:
  version: v0.1
  title: Healthcare Worker API
  description: |
    ## Overview
    Use this API to access details of healthcare workers registered in the [Care Identity Service (CIS)](https://digital.nhs.uk/services/care-identity-service) directory.

    You can:
    - get basic professional details of any healthcare worker with an active care identity, using their unique ID (this is sometimes known as SDS user ID or Smartcard ID).

    You cannot currently use this API to:
    - search by professional codes, such as GMC or RNC code

    The strategic aim of the API is to allow systems to search, retrieve and display healthcare worker data from over 1.4 million NHS employees with a health care profile.
    The objective is to increase data efficiency, business logic and improve interoperability within the business.

    This strategic solution will allow internal and 3rd party systems to access and share information more reliably, flexibly and efficiently while benefiting from improved network and bandwidth capacity, financial savings
    and easier and smoother access to clinical systems.

    ## Who can use this API
    This API can only be used where there is a legal basis to do so. Make sure you have a valid use case before you go too far with your development.

    You must do this before you can go live (see "Onboarding" below).

    ## Related APIs
    The following APIs are related to this one:
    * [Healthcare Worker - FHIR API](https://digital.nhs.uk/developer/api-catalogue/healthcare-fhir-api)

    ## API status and roadmap
    This API is [in alpha](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#statuses).

    To see our roadmap, or to suggest, comment or vote on features for this API, see our [interactive product backlog](https://nhs-digital-api-management.featureupvote.com/suggestions/204411/healthcare-professionals-api).

    If you  have any other queries, [contact us](https://digital.nhs.uk/developer/help-and-support).

    ## Service level
    This API is a bronze service during alpha, meaning it is operational and supported only during business hours (8am to 6pm), Monday to Friday excluding bank holidays.
    Once in beta the API will be a silver service, meaning it is operational 24/7 and supported only during business hours (8am to 6pm), Monday to Friday excluding bank holidays.

    For more details, see [service levels](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#service-levels).

    ## Technology
    This API is [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/our-api-technologies#basic-rest).

    It conforms to the [FHIR](https://digital.nhs.uk/developer/guides-and-documentation/our-api-technologies#fhir) global standard for health care data exchange, specifically to [FHIR R4 (v4.0.1)](https://hl7.org/fhir/r4/), except that it does not support the [capabilities](http://hl7.org/fhir/R4/http.html#capabilities) interaction.

    It includes some country-specific FHIR extensions, which conform to [FHIR UK Core](https://digital.nhs.uk/services/fhir-uk-core), specifically [fhir.r4.ukcore.stu1 0.5.1](https://simplifier.net/packages/fhir.r4.ukcore.stu1/0.5.1).

    You do not need to know much about FHIR to use this API - FHIR APIs are just RESTful APIs that follow specific rules. In particular:
    - resource names are capitalised and singular, for example `/Endpoint` not `/endpoints`

    Errors handling in this API follows [NHS guidelines](https://nhsconnect.github.io/FHIR-SpineCore/resources_error_handling.html) and produces an [OperationOutcome](https://fhir.nhs.uk/STU3/StructureDefinition/Spine-OperationOutcome-1) FHIR resource response with appropriate HTTP code

    ## Network access
    This API is available on the internet and, indirectly, on the [Health and Social Care Network (HSCN).](https://digital.nhs.uk/services/health-and-social-care-network)

    For more details see [Network access for APIs](https://digital.nhs.uk/developer/guides-and-documentation/network-access-for-apis).

    ## Security and authorisation
    This API is [application-restricted](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#application-restricted-apis), meaning we authenticate the calling application but not the end user.

    To use this API, use the following security pattern:

    * [Application-restricted RESTful APIs - signed JWT authentication](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/application-restricted-restful-apis-signed-jwt-authentication)

    ## Postman Collection
    See https://github.com/NHSDigital/healthcare-worker-api/tree/develop/postman for an export of our postman collection. The readme in that directory explains how to set it up and send the requests.

    ## Open source

    You might find the following [open source](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#open-source) resources useful:

    | Resource                | Description                                                   | Links                                                                                                                                        |
    | ----------------------- | ------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------- |
    | Project codebase        | The full Healthcare Worker codebase is open source in GitHub. | [Github](https://github.com/NHSDigital/healthcare-worker-api)                                                                                |
    | FHIR libraries and SDKs | Various open source libraries for integrating with FHIR APIs. | [FHIR libraries and SDKs](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#fhir-libraries-and-sdks) |

    ## Environments and testing
    | Environment       | Base URL
    | ----------------- | ---------------------------------------------------------------------|
    | Sandbox           | `https://sandbox.api.service.nhs.uk/healthcare-worker`               |
    | Integration test  | `https://int.api.service.nhs.uk/healthcare-worker`                   |
    | Production        | `https://api.service.nhs.uk/healthcare-worker`                       |

    ### Sandbox testing
    Our [sandbox environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#sandbox-testing):
    * is for early developer testing
    * only covers a limited set of scenarios
    * is open-access, so does not allow you to test authorisation

    For more details on sandbox testing, or to try out the sandbox using our \"Try this API\" feature, see the documentation for each endpoint.

    ### Integration testing
    Our [integration test environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing):
    - is for formal integration testing.
    - includes application authentication

    ### Deployment and user acceptance testing
    Our deployment environment is for testing applications in-situ before live deployments and also for user acceptance testing (UAT) with NHS organisations.

    This environment is for use by developers who are using the SDS FHIR API alongside some of our older APIs where the deployment environment is already in use,
    for example, developers who have migrated from the [Query Accredited System Information API](https://digital.nhs.uk/developer/api-catalogue/query-accredited-system-information-soap).

    ## Related APIs
    The following APIs are related to this one:- [Spine Directory Service - LDAP API](https://digital.nhs.uk/developer/api-catalogue/spine-directory-service-ldap) - Access details of organisations, people and systems registered in the Spine Directory Service (SDS) using our LDAP API. This API is only available on HSCN, doesn't use the FHIR standard and is being considered for deprecation.
    - [Organisation Data Terminology - FHIR API](https://digital.nhs.uk/developer/api-catalogue/organisation-data-terminology) - Access an organisation-based dataset from the Organisation Data Service (ODS), including some limited information on some prescribing staff at each organisation.
    - [Organisation Data Service - FHIR API](https://digital.nhs.uk/developer/api-catalogue/organisation-data-service-fhir) - Access a reduced organisation-based dataset from the Organisation Data Service (ODS). An older, limited alternative to ODS Terminology API and soon to be deprecated.

    ## Onboarding
    You need to get your software approved by us before it can go live with this API. We call this onboarding. The onboarding process can sometimes be quite long, so it's worth planning well ahead.

    As part of this process, you need to demonstrate that you can manage risks and that your software conforms
    technically with the requirements for this API. This might impact the design of your software. For details, see
    [Onboarding support information](https://digital.nhs.uk/developer/api-catalogue/child-protection-information-sharing-hl7-v3/onboarding-support-information).

    To understand how our online digital onboarding process works, see [digital onboarding](https://digital.nhs.uk/developer/guides-and-documentation/digital-onboarding).

    To get started, sign in or create a [developer account](https://onboarding.prod.api.platform.nhs.uk/), then select 'product onboarding'.

    ## Errors
    We use standard HTTP status codes to show whether an API request succeeded or not. They are usually in the range:

    * 200 to 299 if it succeeded, including code 202 if it was accepted by an API that needs to wait for further action
    * 400 to 499 if it failed because of a client error by your application
    * 500 to 599 if it failed because of an error on our server

    Errors specific to each API are shown in the Endpoints section, under Response. See our [reference guide](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#http-status-codes) for more on errors.
  contact:
    name: Spine Directory Service API Support
    url: https://digital.nhs.uk/developer/help-and-support
    email: api.management@nhs.net
security:
  - app-level3: []
servers:
  - url: https://sandbox.api.service.nhs.uk/healthcare-worker
    description: Sandbox environment
x-nhsd-apim:
  monitoring: true
  access:
    - title: "Application Restricted"
      grants:
        app-level3: []
  target:
    type: external
    healthcheck: /
    url:
    security:
      type: mtls
      secret: hcw-mtls
paths:
  /Practitioner:
    get:
      summary: Get healthcare worker details
      operationId: getPractitioner
      description: |
        # Overview
        Use this endpoint to get details of healthcare workers in the CIS directory.

        This endpoint will return the matching Person object from the directory, which provides the following information:
          * Name
          * Title

        Only active objects, showing details will be returned. If the care identity itself is closed, a 410 response will be returned (see below).

        This endpoint supports the use of the _revinclude query parameter to expose more information about practitioner roles.
        It must take the value of either PractitionerRole:practitioner.

        To get the information, you must supply:
          * CIS unique identifier (sometimes known as SDS user ID or smartcard ID)
      parameters:
        - in: query
          name: identifier
          description: SDS user ID which uniquely identifies a person.
          required: true
          example: 123456789012
          schema:
            type: string
          explode: true
        - in: query
          name: _revinclude
          description: Include objects which reference the one being returned.
          required: false
          example: PractitionerRole:practitioner
          schema:
            type: string
        - in: header
          name: X-Correlation-Id
          description: UUID for request tracking
          schema:
            type: string
            format: uuid
          example: 6d3d3674-7ce5-11ec-90d6-0242ac120003
      responses:
        '200':
          description: Successful operation
          content:
            application/fhir+json:
              schema:
                type: object
                properties:
                  practitioner:
                    $ref: '#/components/schemas/Practitioner'
        '400':
          description: Missing or invalid query parameter(s).
        '404':
          description: Invalid endpoint path
        '405':
          description: Unsupported HTTP method. For this endpoint only GET is available
        '410':
          description: Resource closed. The requested care identity profile is no longer active.
        '500':
          description: Unhandled internal server error
        '502':
          description: Upstream system returned an unsupported response
        '504':
          description: Upstream server request has timed out
  /PractitionerRole:
    get:
      summary: Get healthcare worker role details
      operationId: getPractitionerRole
      description: |
        # Overview
        Use this endpoint to get details of healthcare worker roles in the CIS directory. It takes a practitioner's
        id as input and returns all the roles associated with that practitioner.

        This endpoint supports the use of the _include query parameter to expose more information about referenced
        organisations and practitioners. It must take the value of either PractitionerRole:organization or
        PractitionerRole:practitioner, with multiple values supported.
      parameters:
        - in: query
          name: practitioner.identifier
          description: SDS user ID which uniquely identifies a person.
          required: true
          example: 123456789012
          schema:
            type: string
          explode: true
        - in: query
          name: _include
          description: Include objects which are referenced by the ones being returned.
          required: false
          example: PractitionerRole:practitioner
          schema:
            type: string
        - in: header
          name: X-Correlation-Id
          description: UUID for request tracking
          schema:
            type: string
            format: uuid
          required: true
          example: 6d3d3674-7ce5-11ec-90d6-0242ac120003
      responses:
        '200':
          description: Successful operation
          content:
            application/fhir+json:
              schema:
                type: array
                items:
                  properties:
                    practitioner_role:
                      $ref: '#/components/schemas/PractitionerRole'
components:
  securitySchemes:
    app-level3:
      $ref: https://proxygen.prod.api.platform.nhs.uk/components/securitySchemes/app-level3
  schemas:
    Practitioner:
      type: object
      properties:
        resourceType:
          type: string
          default: Practitioner
        id:
          type: string
          description: Auto generated unique ID for the person.
          example: 123456789012
        identifier:
          type: array
          description: Auto generated unique ID for the person.
          items:
            type: object
            properties:
              system:
                type: string
                default: https://fhir.nhs.uk/Id/sds-user-id
              value:
                type: string
                example: 123456789012
        active:
          type: boolean
          description: Describes the active status of the Practitioner record in the directory.
          example: True
        name:
          type: array
          description: Person's name details.
          items:
            type: object
            properties:
              use:
                type: string
                description: Identifies the purpose for this name.
                default: usual
              family:
                type: string
                description: That part of a person's name which is used to describe family, clan, tribal group, or marital association.
                example: Smith
              given:
                type: string
                description: The forenames or given names of a person. Includes middle names.
                example: Jane Alison
              prefix:
                type: string
                description: Standard form of address used to precede a person's name
                example: Ms
    PractitionerRole:
      type: object
      properties:
        resourceType:
          type: string
          default: PractitionerRole
        id:
          type: string
          description: Id of the practitioner role
        identifier:
          type: array
          description: Auto generated unique ID for the role.
          items:
            type: object
            properties:
              system:
                type: string
                default: https://fhir.nhs.uk/Id/sds-role-profile-id
              value:
                type: string
                example: 123456789012
        active:
          type: boolean
          description: Describes the active status of the Practitioner record in the directory.
          example: True
        practitioner:
          $ref: '#/components/schemas/Reference'
        organization:
          $ref: '#/components/schemas/Reference'
        period:
          type: object
          properties:
              start:
                type: string
              end:
                type: string
        code:
          type: array
          items:
            $ref: '#/components/schemas/CodeableConcept'
    Reference:
      type: object
      properties:
        resourceType:
          type: string
          default: Identifier
        system:
          type: string
        value:
          type: string
    CodeableConcept:
      type: object
      properties:
        resourceType:
          type: string
          default: CodeableConcept
        coding:
          type: object
          properties:
            resourceType:
              type: string
              default: Coding
            system:
              type: string
            code:
              type: string
            display:
              type: string
