name: "Perform static analysis"
description: "Perform static analysis"
inputs:
  sonar_organisation_key:
    description: "Sonar organisation key, used to identify the project"
    required: false
  sonar_project_key:
    description: "Sonar project key, used to identify the project"
    required: false
  sonar_token:
    description: "Sonar token, the API key"
    required: false
runs:
  using: "composite"
  steps:
    - name: "Check prerequisites for performing static analysis"
      shell: bash
      id: check
      run: echo "secret_exist=${{ inputs.sonar_token != '' }}" >> $GITHUB_OUTPUT
    - name: Set up Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: "22"
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: "Perform static analysis"
      shell: bash
      if: steps.check.outputs.secret_exist == 'true'
      run: |
        pip install pipx
        python -m pipx install poetry
        python -m pipx ensurepath
        source ~/.bashrc
        poetry install

        export BRANCH_NAME=${GITHUB_HEAD_REF:-$(echo $GITHUB_REF | sed 's#refs/heads/##')}
        export SONAR_ORGANISATION_KEY=${{ inputs.sonar_organisation_key }}
        export SONAR_PROJECT_KEY=${{ inputs.sonar_project_key }}
        export SONAR_TOKEN=${{ inputs.sonar_token }}
        if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
          export PULL_REQUEST_NUMBER=$(echo $GITHUB_REF | sed 's#refs/pull/##' | sed 's#/merge##')
        fi

        poetry run coverage run -m pytest
        poetry run coverage xml
        ./scripts/reports/perform-static-analysis.sh
    - name: "Install Trivy"
      shell: bash
      run: |
        sudo apt-get install -y wget apt-transport-https gnupg
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install -y trivy
        trivy --version
    - name: "Run Trivy Checks"
      uses: aquasecurity/trivy-action@0.34.1
      with:
        scan-type: "config"
        format: "sarif"
        output: trivy.sarif
        skip-setup-trivy: true
      env:
        TRIVY_SKIP_DB_UPDATE: true
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy.sarif'
